### ISSUE TITLE
E960: not an open channel

### ISSUE THREAD

**Issue by qqqays** [AndrewRadev/gnugo.vim#1]
processing function <SNR>23_Gnugo[9]..gnugo#Init[21]..gnugo#runner#Redraw had error.
at 1 line:
E960: not an open channel

**Comment by AndrewRadev** [comment]
This might be difficult to debug. Could you give me some more information about the problem?

- What is your Vim version?
- Do you have the `gnugo` program installed on your computer?
- What is the command that you used when you got the error? It seems like it happens when you start a new game with `:Gnugo`. Is that right?
- Does this happen all the time, or only sometimes?
