### ISSUE TITLE
Resume game does not work?

### ISSUE THREAD

**Issue by pcace** [AndrewRadev/gnugo.vim#4]
Hi, i am new to vim, but how can i resume a game? When i open an sqt file i saved earlier, vim just opens it as a text file, it does not ask to resume the game...
Any idea how to solve that?
Cheers and thanks!

**Comment by AndrewRadev** [comment]
The plugin tries to automatically load flies with the `.sgf` extension, because that's the extension I saw in gnugo examples, I think. It's a bit hidden in terms of functionality, though, I was even trying to figure it out recently myself :+1: 

I've just added a new command, `:GnugoLoad` that you can use to load a savegame file. So, if you open vim and run `:GnugoLoad <filename>`, it should resume the game. Could you try it out and let me know if it works.

**Comment by pcace** [comment]
years later ;) 

> 
> I've just added a new command, `:GnugoLoad` that you can use to load a savegame file. So, if you open vim and run `:GnugoLoad <filename>`, it should resume the game. Could you try it out and let me know if it works.

works ;)

**Comment by AndrewRadev** [comment]
Hey, better late than never :) :+1:
